// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Context;

#nullable disable

namespace GoalHub_API.Migrations
{
    [DbContext(typeof(GoalHubSQLContext))]
    [Migration("20251103095632_AddIsDeletedToTeams")]
    partial class AddIsDeletedToTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.City", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ID"));

                    b.Property<short>("CountryID")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = (short)1,
                            CountryID = (short)1,
                            Name = "Berlin"
                        },
                        new
                        {
                            ID = (short)2,
                            CountryID = (short)1,
                            Name = "Munich"
                        },
                        new
                        {
                            ID = (short)3,
                            CountryID = (short)1,
                            Name = "Hamburg"
                        },
                        new
                        {
                            ID = (short)4,
                            CountryID = (short)1,
                            Name = "Cologne"
                        },
                        new
                        {
                            ID = (short)5,
                            CountryID = (short)1,
                            Name = "Frankfurt"
                        },
                        new
                        {
                            ID = (short)6,
                            CountryID = (short)2,
                            Name = "Madrid"
                        },
                        new
                        {
                            ID = (short)7,
                            CountryID = (short)2,
                            Name = "Barcelona"
                        },
                        new
                        {
                            ID = (short)8,
                            CountryID = (short)2,
                            Name = "Valencia"
                        },
                        new
                        {
                            ID = (short)9,
                            CountryID = (short)2,
                            Name = "Seville"
                        },
                        new
                        {
                            ID = (short)10,
                            CountryID = (short)2,
                            Name = "Zaragoza"
                        },
                        new
                        {
                            ID = (short)11,
                            CountryID = (short)3,
                            Name = "Paris"
                        },
                        new
                        {
                            ID = (short)12,
                            CountryID = (short)3,
                            Name = "Marseille"
                        },
                        new
                        {
                            ID = (short)13,
                            CountryID = (short)3,
                            Name = "Lyon"
                        },
                        new
                        {
                            ID = (short)14,
                            CountryID = (short)3,
                            Name = "Toulouse"
                        },
                        new
                        {
                            ID = (short)15,
                            CountryID = (short)3,
                            Name = "Nice"
                        },
                        new
                        {
                            ID = (short)16,
                            CountryID = (short)4,
                            Name = "London"
                        },
                        new
                        {
                            ID = (short)17,
                            CountryID = (short)4,
                            Name = "Birmingham"
                        },
                        new
                        {
                            ID = (short)18,
                            CountryID = (short)4,
                            Name = "Manchester"
                        },
                        new
                        {
                            ID = (short)19,
                            CountryID = (short)4,
                            Name = "Liverpool"
                        },
                        new
                        {
                            ID = (short)20,
                            CountryID = (short)5,
                            Name = "Rome"
                        },
                        new
                        {
                            ID = (short)21,
                            CountryID = (short)5,
                            Name = "Milan"
                        },
                        new
                        {
                            ID = (short)22,
                            CountryID = (short)5,
                            Name = "Naples"
                        },
                        new
                        {
                            ID = (short)23,
                            CountryID = (short)5,
                            Name = "Turin"
                        },
                        new
                        {
                            ID = (short)24,
                            CountryID = (short)5,
                            Name = "Florence"
                        },
                        new
                        {
                            ID = (short)25,
                            CountryID = (short)6,
                            Name = "Lisbon"
                        },
                        new
                        {
                            ID = (short)26,
                            CountryID = (short)6,
                            Name = "Porto"
                        },
                        new
                        {
                            ID = (short)27,
                            CountryID = (short)7,
                            Name = "Amsterdam"
                        },
                        new
                        {
                            ID = (short)28,
                            CountryID = (short)7,
                            Name = "Rotterdam"
                        },
                        new
                        {
                            ID = (short)29,
                            CountryID = (short)8,
                            Name = "Brussels"
                        },
                        new
                        {
                            ID = (short)30,
                            CountryID = (short)8,
                            Name = "Antwerp"
                        },
                        new
                        {
                            ID = (short)31,
                            CountryID = (short)9,
                            Name = "Moscow"
                        },
                        new
                        {
                            ID = (short)32,
                            CountryID = (short)9,
                            Name = "Saint Petersburg"
                        },
                        new
                        {
                            ID = (short)33,
                            CountryID = (short)9,
                            Name = "Kazan"
                        },
                        new
                        {
                            ID = (short)34,
                            CountryID = (short)10,
                            Name = "Istanbul"
                        },
                        new
                        {
                            ID = (short)35,
                            CountryID = (short)10,
                            Name = "Ankara"
                        },
                        new
                        {
                            ID = (short)36,
                            CountryID = (short)10,
                            Name = "Izmir"
                        },
                        new
                        {
                            ID = (short)37,
                            CountryID = (short)11,
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            ID = (short)38,
                            CountryID = (short)11,
                            Name = "Córdoba"
                        },
                        new
                        {
                            ID = (short)39,
                            CountryID = (short)12,
                            Name = "São Paulo"
                        },
                        new
                        {
                            ID = (short)40,
                            CountryID = (short)12,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            ID = (short)41,
                            CountryID = (short)12,
                            Name = "Brasília"
                        },
                        new
                        {
                            ID = (short)42,
                            CountryID = (short)12,
                            Name = "Salvador"
                        },
                        new
                        {
                            ID = (short)43,
                            CountryID = (short)12,
                            Name = "Fortaleza"
                        },
                        new
                        {
                            ID = (short)44,
                            CountryID = (short)13,
                            Name = "Mexico City"
                        },
                        new
                        {
                            ID = (short)45,
                            CountryID = (short)13,
                            Name = "Guadalajara"
                        },
                        new
                        {
                            ID = (short)46,
                            CountryID = (short)13,
                            Name = "Monterrey"
                        },
                        new
                        {
                            ID = (short)47,
                            CountryID = (short)14,
                            Name = "New York"
                        },
                        new
                        {
                            ID = (short)48,
                            CountryID = (short)14,
                            Name = "Los Angeles"
                        },
                        new
                        {
                            ID = (short)49,
                            CountryID = (short)14,
                            Name = "Chicago"
                        },
                        new
                        {
                            ID = (short)50,
                            CountryID = (short)14,
                            Name = "Houston"
                        },
                        new
                        {
                            ID = (short)51,
                            CountryID = (short)14,
                            Name = "Miami"
                        },
                        new
                        {
                            ID = (short)52,
                            CountryID = (short)15,
                            Name = "Edinburgh"
                        },
                        new
                        {
                            ID = (short)53,
                            CountryID = (short)15,
                            Name = "Glasgow"
                        },
                        new
                        {
                            ID = (short)54,
                            CountryID = (short)16,
                            Name = "Athens"
                        },
                        new
                        {
                            ID = (short)55,
                            CountryID = (short)16,
                            Name = "Thessaloniki"
                        },
                        new
                        {
                            ID = (short)56,
                            CountryID = (short)17,
                            Name = "Zurich"
                        },
                        new
                        {
                            ID = (short)57,
                            CountryID = (short)17,
                            Name = "Geneva"
                        },
                        new
                        {
                            ID = (short)58,
                            CountryID = (short)18,
                            Name = "Vienna"
                        },
                        new
                        {
                            ID = (short)59,
                            CountryID = (short)18,
                            Name = "Salzburg"
                        },
                        new
                        {
                            ID = (short)60,
                            CountryID = (short)19,
                            Name = "Copenhagen"
                        },
                        new
                        {
                            ID = (short)61,
                            CountryID = (short)20,
                            Name = "Oslo"
                        },
                        new
                        {
                            ID = (short)62,
                            CountryID = (short)21,
                            Name = "Stockholm"
                        },
                        new
                        {
                            ID = (short)63,
                            CountryID = (short)21,
                            Name = "Gothenburg"
                        },
                        new
                        {
                            ID = (short)64,
                            CountryID = (short)22,
                            Name = "Warsaw"
                        },
                        new
                        {
                            ID = (short)65,
                            CountryID = (short)22,
                            Name = "Krakow"
                        },
                        new
                        {
                            ID = (short)66,
                            CountryID = (short)23,
                            Name = "Kyiv"
                        },
                        new
                        {
                            ID = (short)67,
                            CountryID = (short)23,
                            Name = "Lviv"
                        },
                        new
                        {
                            ID = (short)68,
                            CountryID = (short)24,
                            Name = "Belgrade"
                        },
                        new
                        {
                            ID = (short)69,
                            CountryID = (short)25,
                            Name = "Zagreb"
                        },
                        new
                        {
                            ID = (short)70,
                            CountryID = (short)26,
                            Name = "Prague"
                        },
                        new
                        {
                            ID = (short)71,
                            CountryID = (short)27,
                            Name = "Tokyo"
                        },
                        new
                        {
                            ID = (short)72,
                            CountryID = (short)27,
                            Name = "Osaka"
                        },
                        new
                        {
                            ID = (short)73,
                            CountryID = (short)27,
                            Name = "Kyoto"
                        },
                        new
                        {
                            ID = (short)74,
                            CountryID = (short)27,
                            Name = "Yokohama"
                        },
                        new
                        {
                            ID = (short)75,
                            CountryID = (short)27,
                            Name = "Nagoya"
                        },
                        new
                        {
                            ID = (short)76,
                            CountryID = (short)28,
                            Name = "Seoul"
                        },
                        new
                        {
                            ID = (short)77,
                            CountryID = (short)28,
                            Name = "Busan"
                        },
                        new
                        {
                            ID = (short)78,
                            CountryID = (short)29,
                            Name = "Shanghai"
                        },
                        new
                        {
                            ID = (short)79,
                            CountryID = (short)29,
                            Name = "Beijing"
                        },
                        new
                        {
                            ID = (short)80,
                            CountryID = (short)29,
                            Name = "Guangzhou"
                        },
                        new
                        {
                            ID = (short)81,
                            CountryID = (short)29,
                            Name = "Shenzhen"
                        },
                        new
                        {
                            ID = (short)82,
                            CountryID = (short)29,
                            Name = "Chengdu"
                        },
                        new
                        {
                            ID = (short)83,
                            CountryID = (short)30,
                            Name = "Sydney"
                        },
                        new
                        {
                            ID = (short)84,
                            CountryID = (short)30,
                            Name = "Melbourne"
                        },
                        new
                        {
                            ID = (short)85,
                            CountryID = (short)30,
                            Name = "Brisbane"
                        },
                        new
                        {
                            ID = (short)86,
                            CountryID = (short)30,
                            Name = "Perth"
                        },
                        new
                        {
                            ID = (short)87,
                            CountryID = (short)30,
                            Name = "Adelaide"
                        },
                        new
                        {
                            ID = (short)88,
                            CountryID = (short)31,
                            Name = "Riyadh"
                        },
                        new
                        {
                            ID = (short)89,
                            CountryID = (short)31,
                            Name = "Jeddah"
                        },
                        new
                        {
                            ID = (short)90,
                            CountryID = (short)32,
                            Name = "Cairo"
                        },
                        new
                        {
                            ID = (short)91,
                            CountryID = (short)32,
                            Name = "Alexandria"
                        },
                        new
                        {
                            ID = (short)92,
                            CountryID = (short)4,
                            Name = "Sheffield"
                        },
                        new
                        {
                            ID = (short)93,
                            CountryID = (short)5,
                            Name = "Bologna"
                        },
                        new
                        {
                            ID = (short)94,
                            CountryID = (short)14,
                            Name = "Philadelphia"
                        },
                        new
                        {
                            ID = (short)95,
                            CountryID = (short)14,
                            Name = "Dallas"
                        },
                        new
                        {
                            ID = (short)96,
                            CountryID = (short)9,
                            Name = "Novosibirsk"
                        },
                        new
                        {
                            ID = (short)97,
                            CountryID = (short)1,
                            Name = "Stuttgart"
                        },
                        new
                        {
                            ID = (short)98,
                            CountryID = (short)3,
                            Name = "Bordeaux"
                        },
                        new
                        {
                            ID = (short)99,
                            CountryID = (short)2,
                            Name = "Málaga"
                        },
                        new
                        {
                            ID = (short)100,
                            CountryID = (short)12,
                            Name = "Curitiba"
                        });
                });

            modelBuilder.Entity("Entities.Models.Coach", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CurrentTeamID")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("CurrentTeamID");

                    b.HasIndex("PersonID");

                    b.ToTable("Coachs");
                });

            modelBuilder.Entity("Entities.Models.Competition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<short>("CountryID")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("EndYear")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("StartYear")
                        .HasColumnType("date");

                    b.Property<short>("TypeID")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TypeID");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("Entities.Models.CompetitionType", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ID");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CompetitionTypes");

                    b.HasData(
                        new
                        {
                            ID = (short)1,
                            Description = "A regular season competition where teams play each other over multiple rounds to determine the champion.",
                            Name = "League"
                        },
                        new
                        {
                            ID = (short)2,
                            Description = "A knockout-style tournament where teams compete in elimination rounds until one winner remains.",
                            Name = "Cup"
                        },
                        new
                        {
                            ID = (short)3,
                            Description = "A one-off match between the winners of the league and cup competitions.",
                            Name = "Super Cup"
                        },
                        new
                        {
                            ID = (short)4,
                            Description = "A non-competitive match often used for practice, preseason, or charity purposes.",
                            Name = "Friendly"
                        });
                });

            modelBuilder.Entity("Entities.Models.Contract", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerID"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Salary")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("PlayerID");

                    b.HasIndex("TeamID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Entities.Models.Country", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Nationality")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            ID = (short)1,
                            Name = "Germany",
                            Nationality = "German"
                        },
                        new
                        {
                            ID = (short)2,
                            Name = "Spain",
                            Nationality = "Spanish"
                        },
                        new
                        {
                            ID = (short)3,
                            Name = "France",
                            Nationality = "French"
                        },
                        new
                        {
                            ID = (short)4,
                            Name = "England",
                            Nationality = "English"
                        },
                        new
                        {
                            ID = (short)5,
                            Name = "Italy",
                            Nationality = "Italian"
                        },
                        new
                        {
                            ID = (short)6,
                            Name = "Portugal",
                            Nationality = "Portuguese"
                        },
                        new
                        {
                            ID = (short)7,
                            Name = "Netherlands",
                            Nationality = "Dutch"
                        },
                        new
                        {
                            ID = (short)8,
                            Name = "Belgium",
                            Nationality = "Belgian"
                        },
                        new
                        {
                            ID = (short)9,
                            Name = "Russia",
                            Nationality = "Russian"
                        },
                        new
                        {
                            ID = (short)10,
                            Name = "Turkey",
                            Nationality = "Turkish"
                        },
                        new
                        {
                            ID = (short)11,
                            Name = "Argentina",
                            Nationality = "Argentine"
                        },
                        new
                        {
                            ID = (short)12,
                            Name = "Brazil",
                            Nationality = "Brazilian"
                        },
                        new
                        {
                            ID = (short)13,
                            Name = "Mexico",
                            Nationality = "Mexican"
                        },
                        new
                        {
                            ID = (short)14,
                            Name = "USA",
                            Nationality = "American"
                        },
                        new
                        {
                            ID = (short)15,
                            Name = "Scotland",
                            Nationality = "Scottish"
                        },
                        new
                        {
                            ID = (short)16,
                            Name = "Greece",
                            Nationality = "Greek"
                        },
                        new
                        {
                            ID = (short)17,
                            Name = "Switzerland",
                            Nationality = "Swiss"
                        },
                        new
                        {
                            ID = (short)18,
                            Name = "Austria",
                            Nationality = "Austrian"
                        },
                        new
                        {
                            ID = (short)19,
                            Name = "Denmark",
                            Nationality = "Danish"
                        },
                        new
                        {
                            ID = (short)20,
                            Name = "Norway",
                            Nationality = "Norwegian"
                        },
                        new
                        {
                            ID = (short)21,
                            Name = "Sweden",
                            Nationality = "Swedish"
                        },
                        new
                        {
                            ID = (short)22,
                            Name = "Poland",
                            Nationality = "Polish"
                        },
                        new
                        {
                            ID = (short)23,
                            Name = "Ukraine",
                            Nationality = "Ukrainian"
                        },
                        new
                        {
                            ID = (short)24,
                            Name = "Serbia",
                            Nationality = "Serbian"
                        },
                        new
                        {
                            ID = (short)25,
                            Name = "Croatia",
                            Nationality = "Croatian"
                        },
                        new
                        {
                            ID = (short)26,
                            Name = "Czech Republic",
                            Nationality = "Czech"
                        },
                        new
                        {
                            ID = (short)27,
                            Name = "Japan",
                            Nationality = "Japanese"
                        },
                        new
                        {
                            ID = (short)28,
                            Name = "South Korea",
                            Nationality = "Korean"
                        },
                        new
                        {
                            ID = (short)29,
                            Name = "China",
                            Nationality = "Chinese"
                        },
                        new
                        {
                            ID = (short)30,
                            Name = "Australia",
                            Nationality = "Australian"
                        },
                        new
                        {
                            ID = (short)31,
                            Name = "Saudi Arabia",
                            Nationality = "Saudi"
                        },
                        new
                        {
                            ID = (short)32,
                            Name = "Egypt",
                            Nationality = "Egyptian"
                        });
                });

            modelBuilder.Entity("Entities.Models.Match", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("AwayTeamID")
                        .HasColumnType("int");

                    b.Property<byte>("AwayTeamScore")
                        .HasColumnType("tinyint");

                    b.Property<int>("CompetitionID")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamID")
                        .HasColumnType("int");

                    b.Property<byte>("HomeTeamScore")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("KickoffTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("StadiumID")
                        .HasColumnType("smallint");

                    b.Property<short>("StatusID")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.HasIndex("AwayTeamID");

                    b.HasIndex("CompetitionID");

                    b.HasIndex("HomeTeamID");

                    b.HasIndex("StadiumID");

                    b.HasIndex("StatusID");

                    b.ToTable("Matchs");
                });

            modelBuilder.Entity("Entities.Models.MatchStatus", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ID");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MatchStatuses");

                    b.HasData(
                        new
                        {
                            ID = (short)1,
                            Description = "The match is planned and scheduled to take place in the future.",
                            Name = "Scheduled"
                        },
                        new
                        {
                            ID = (short)2,
                            Description = "The match is currently in progress.",
                            Name = "Live"
                        },
                        new
                        {
                            ID = (short)3,
                            Description = "The match has ended and the final result is recorded.",
                            Name = "Finished"
                        },
                        new
                        {
                            ID = (short)4,
                            Description = "The match was canceled and will not take place.",
                            Name = "Canceled"
                        },
                        new
                        {
                            ID = (short)5,
                            Description = "The match has been temporarily stopped and will continue later; the time already played will still count.",
                            Name = "Postponed"
                        });
                });

            modelBuilder.Entity("Entities.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<short>("CountryID")
                        .HasColumnType("smallint")
                        .HasColumnName("CountryID");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.HasIndex("Name");

                    b.HasIndex("Photo")
                        .IsUnique();

                    b.ToTable("People");
                });

            modelBuilder.Entity("Entities.Models.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CurrentTeamID")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<byte>("ShirtNumber")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.HasIndex("CurrentTeamID");

                    b.HasIndex("PersonID");

                    b.HasIndex("Position");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Entities.Models.PlayerStatus", b =>
                {
                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.Property<short?>("Assists")
                        .HasColumnType("smallint");

                    b.Property<short?>("Goals")
                        .HasColumnType("smallint");

                    b.Property<byte?>("RedCards")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("YellowCards")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerID");

                    b.ToTable("PlayerStatuses");
                });

            modelBuilder.Entity("Entities.Models.Stadium", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<short>("CityID")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Stadiums");
                });

            modelBuilder.Entity("Entities.Models.Team", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<short>("CityID")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("FoundedDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<short>("StadiumID")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.HasIndex("Logo")
                        .IsUnique()
                        .HasFilter("[Logo] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StadiumID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Entities.Models.TransferRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("ApplyingDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("Date");

                    b.Property<int>("FromTeamID")
                        .HasColumnType("int");

                    b.Property<string>("PDFDocument")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.Property<short>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<int>("ToTeamID")
                        .HasColumnType("int");

                    b.Property<decimal>("TransferFee")
                        .HasColumnType("money");

                    b.HasKey("ID");

                    b.HasIndex("FromTeamID");

                    b.HasIndex("PDFDocument")
                        .IsUnique();

                    b.HasIndex("PlayerID");

                    b.HasIndex("StatusID");

                    b.HasIndex("ToTeamID");

                    b.ToTable("TransferRequests");
                });

            modelBuilder.Entity("Entities.Models.TransferStatus", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ID");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TransferStatuses");

                    b.HasData(
                        new
                        {
                            ID = (short)1,
                            Description = "Transfer request has been approved.",
                            Name = "Accepted"
                        },
                        new
                        {
                            ID = (short)2,
                            Description = "Transfer request has been canceled.",
                            Name = "Canceled"
                        },
                        new
                        {
                            ID = (short)3,
                            Description = "Transfer request has been rejected.",
                            Name = "Rejected"
                        },
                        new
                        {
                            ID = (short)4,
                            Description = "Transfer request is awaiting approval.",
                            Name = "Pending"
                        });
                });

            modelBuilder.Entity("Entities.Models.City", b =>
                {
                    b.HasOne("Entities.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Entities.Models.Coach", b =>
                {
                    b.HasOne("Entities.Models.Team", "CurrentTeam")
                        .WithMany()
                        .HasForeignKey("CurrentTeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentTeam");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entities.Models.Competition", b =>
                {
                    b.HasOne("Entities.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.CompetitionType", "TypeInfo")
                        .WithMany()
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("TypeInfo");
                });

            modelBuilder.Entity("Entities.Models.Contract", b =>
                {
                    b.HasOne("Entities.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Entities.Models.Match", b =>
                {
                    b.HasOne("Entities.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.Stadium", "Stadium")
                        .WithMany()
                        .HasForeignKey("StadiumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.MatchStatus", "MatchStatus")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("HomeTeam");

                    b.Navigation("MatchStatus");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("Entities.Models.Person", b =>
                {
                    b.HasOne("Entities.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Entities.Models.Player", b =>
                {
                    b.HasOne("Entities.Models.Team", "CurrentTeam")
                        .WithMany()
                        .HasForeignKey("CurrentTeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentTeam");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entities.Models.PlayerStatus", b =>
                {
                    b.HasOne("Entities.Models.Player", "Player")
                        .WithOne("Status")
                        .HasForeignKey("Entities.Models.PlayerStatus", "PlayerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Entities.Models.Stadium", b =>
                {
                    b.HasOne("Entities.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Entities.Models.Team", b =>
                {
                    b.HasOne("Entities.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.Stadium", "Stadium")
                        .WithMany()
                        .HasForeignKey("StadiumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("Entities.Models.TransferRequest", b =>
                {
                    b.HasOne("Entities.Models.Team", "FromTeam")
                        .WithMany()
                        .HasForeignKey("FromTeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.TransferStatus", "StatusInfo")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.Team", "ToTeam")
                        .WithMany()
                        .HasForeignKey("ToTeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromTeam");

                    b.Navigation("Player");

                    b.Navigation("StatusInfo");

                    b.Navigation("ToTeam");
                });

            modelBuilder.Entity("Entities.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Entities.Models.Player", b =>
                {
                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
